.\" Manpage for fsh's cd command
.\" (C) 2024 Le Bao Nguyen.

.TH man 1

.SH NAME
cd - short name of 'change directory'

.SH SYNOSIS
cd [directory]

.SH DESCRIPTION
Switches the current working directory to something else (most times, yeah why cd .?)

Return codes:

* Zero on success;

* Else check man fsh for IOResult codes.