.\" Manpage for fsh program
.\" (C) 2024 Le Bao Nguyen.

.TH man 1

.SH NAME
fsh/FPSH - the Free Pascal Shell

.SH SYNOSIS
fsh [flags] [value/commands]

.SH DESCRIPTION
fsh is a shell entirely written in Objective Pascal. It has does many things that other shells can, but except an own scripting language.

.SH OPTIONS
Currently no options available, but soon via command-line flags and ~/.fshrc.

.SH BUGS
No known bugs.

.SH SEE ALSO
fsh-cd(1), fsh-codes(2)

.SH AUTHOR
Le Bao Nguyen